import type { Pet, Shelter } from "./types";

export const SHELTERS: Shelter[] = [
  {
    id: "sh-1",
    name: "Pacific Coast SPCA — Vancouver",
    location: "1205 East 7th Ave",
    city: "Vancouver",
    verified: true,
    description:
      "A community-funded shelter providing care for surrendered and rescued animals across Metro Vancouver. We focus on thoughtful matches and lifelong support for adopters.",
    phone: "(604) 555-0142",
    email: "adopt@pacificcoastspca.example",
    website: "pacificcoastspca.example",
    hours: "Tue–Sun, 11am–6pm",
    adoptionProcess: [
      "Submit an interest form",
      "Phone or video screening",
      "In-person meet-and-greet",
      "Home environment check",
      "Adoption paperwork & welcome kit",
    ],
    animalTypes: ["dog", "cat", "small"],
    responseTime: "Typically replies within 2 business days",
    petsAvailable: 24,
    accent: "from-primary/15 to-primary/5",
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "sh-2",
    name: "Orphan Kitten Project",
    location: "2340 Main St",
    city: "Vancouver",
    verified: true,
    description:
      "Foster-based rescue dedicated to neonatal kittens and bonded pairs. All cats are vetted, socialized, and placed through careful adopter matching.",
    phone: "(604) 555-0188",
    email: "hello@orphankitten.example",
    website: "orphankitten.example",
    hours: "By appointment",
    adoptionProcess: [
      "Browse available kittens",
      "Submit interest form",
      "Foster-led video call",
      "Meet-and-greet at foster home",
      "Adoption with starter kit",
    ],
    animalTypes: ["cat"],
    responseTime: "Typically replies within 3 business days",
    petsAvailable: 18,
    accent: "from-accent/15 to-accent/5",
    createdAt: "2024-10-01T00:00:00Z",
  },
  {
    id: "sh-3",
    name: "Richmond Animal Protection Society",
    location: "12071 No. 5 Rd",
    city: "Richmond",
    verified: true,
    description:
      "Independent no-kill shelter caring for dogs and cats across Richmond and the South Arm. Strong emphasis on rehabilitation and matchmaking.",
    phone: "(604) 555-0220",
    email: "adopt@raps.example",
    website: "raps.example",
    hours: "Daily, 10am–5pm",
    adoptionProcess: ["Apply online", "Meet your match", "Trial visit", "Adoption finalization"],
    animalTypes: ["dog", "cat"],
    responseTime: "Replies within 3 business days",
    petsAvailable: 31,
    accent: "from-info/15 to-info/5",
    createdAt: "2024-08-15T00:00:00Z",
  },
  {
    id: "sh-4",
    name: "North Shore Paws Rescue",
    location: "131 W 14th St",
    city: "North Vancouver",
    verified: true,
    description:
      "Volunteer-run rescue across the North Shore. We rehome dogs from rural BC and transport partners, prioritizing calm urban homes.",
    phone: "(604) 555-0309",
    email: "hello@northshorepaws.example",
    website: "northshorepaws.example",
    hours: "Weekends + by appointment",
    adoptionProcess: ["Application", "Reference check", "Trail walk meet", "2-week trial"],
    animalTypes: ["dog"],
    responseTime: "Replies within 4 business days",
    petsAvailable: 9,
    accent: "from-primary/15 to-info/10",
    createdAt: "2024-11-01T00:00:00Z",
  },
  {
    id: "sh-5",
    name: "Burnaby Friends of Felines",
    location: "5100 Kingsway",
    city: "Burnaby",
    verified: true,
    description:
      "Cat-focused rescue with a thriving foster network across Burnaby and New Westminster. Bonded pairs and senior cats are our specialty.",
    phone: "(604) 555-0410",
    email: "adopt@bfof.example",
    website: "bfof.example",
    hours: "Wed–Sun, noon–6pm",
    adoptionProcess: ["Interest form", "Foster intro", "Home visit", "Adoption"],
    animalTypes: ["cat"],
    responseTime: "Replies within 2 business days",
    petsAvailable: 22,
    accent: "from-accent/15 to-warning/10",
    createdAt: "2024-07-22T00:00:00Z",
  },
  {
    id: "sh-6",
    name: "Lower Mainland Rabbit Rescue",
    location: "Mobile across the LM",
    city: "Coquitlam",
    verified: true,
    description:
      "BC's only fully volunteer-run rabbit rescue. Bonded pairs, dietary education, and lifelong bunny support.",
    phone: "(604) 555-0511",
    email: "adopt@lmrr.example",
    website: "lmrr.example",
    hours: "Foster-based — by appointment",
    adoptionProcess: ["Application", "Habitat check", "Bonding session", "Adoption with care guide"],
    animalTypes: ["rabbit", "small"],
    responseTime: "Replies within 5 business days",
    petsAvailable: 12,
    accent: "from-primary/10 to-accent/10",
    createdAt: "2024-06-10T00:00:00Z",
  },
];

// Gradient backgrounds keyed by species so cards look beautiful without external photos.
export const speciesGradient: Record<Pet["species"], string> = {
  dog: "from-orange-200 via-amber-100 to-rose-100",
  cat: "from-teal-100 via-sky-100 to-indigo-100",
  rabbit: "from-pink-100 via-rose-100 to-amber-100",
  small: "from-lime-100 via-emerald-100 to-teal-100",
};

const today = new Date();
const daysAgo = (n: number) => new Date(today.getTime() - n * 86400000).toISOString();

export const PETS: Pet[] = [
  {
    id: "p-mochi",
    name: "Mochi",
    species: "dog",
    breed: "Shiba Inu mix",
    age: "2 years",
    ageGroup: "young",
    gender: "female",
    size: "small",
    weightKg: 9,
    energyLevel: "medium",
    locationCity: "Vancouver",
    distanceKm: 3,
    shelterId: "sh-1",
    shelterName: "Pacific Coast SPCA — Vancouver",
    images: ["g1", "g2", "g3"],
    bio: "Mochi loves slow morning walks, sunny patios, and a quiet apartment to nap in. She greets new people gently and has a soft, curious personality.",
    idealHome: "A calm adult home or couple. OK with one resident cat after intro.",
    personalityTags: ["Gentle", "Curious", "Apartment-friendly"],
    goodWithDogs: true,
    goodWithCats: true,
    goodWithKids: false,
    medicalNotes: "Healthy. Mild seasonal allergies managed by diet.",
    vaccinated: true,
    spayedNeutered: true,
    meetAndGreet: "At the shelter, by appointment",
    adoptionFee: 450,
    status: "available",
    lastUpdated: daysAgo(2),
    createdAt: daysAgo(40),
  },
  {
    id: "p-luna",
    name: "Luna",
    species: "cat",
    breed: "Domestic shorthair",
    age: "3 years",
    ageGroup: "adult",
    gender: "female",
    size: "small",
    weightKg: 4,
    energyLevel: "low",
    locationCity: "Vancouver",
    distanceKm: 4,
    shelterId: "sh-2",
    shelterName: "Orphan Kitten Project",
    images: ["g1", "g2"],
    bio: "Luna is a velvet-soft tuxedo who loves window-sill afternoons and slow chin rubs. She purrs as soon as you sit down.",
    idealHome: "Quiet home, can be only-cat or paired with calm cat.",
    personalityTags: ["Calm", "Affectionate", "Lap cat"],
    goodWithDogs: false,
    goodWithCats: true,
    goodWithKids: true,
    medicalNotes: "Healthy. Annual dental cleaning recommended.",
    vaccinated: true,
    spayedNeutered: true,
    meetAndGreet: "Foster home, East Vancouver",
    adoptionFee: 180,
    status: "available",
    lastUpdated: daysAgo(1),
    createdAt: daysAgo(20),
  },
  {
    id: "p-bear",
    name: "Bear",
    species: "dog",
    breed: "Bernese mix",
    age: "4 years",
    ageGroup: "adult",
    gender: "male",
    size: "large",
    weightKg: 38,
    energyLevel: "medium",
    locationCity: "North Vancouver",
    distanceKm: 12,
    shelterId: "sh-4",
    shelterName: "North Shore Paws Rescue",
    images: ["g1", "g2", "g3"],
    bio: "Bear is a gentle giant who lives for forest trails and back-porch naps. He's perfect for a North Shore family who loves to hike.",
    idealHome: "House with yard or active hiking household. Loves rain.",
    personalityTags: ["Goofy", "Hiker", "Gentle giant"],
    goodWithDogs: true,
    goodWithCats: false,
    goodWithKids: true,
    medicalNotes: "Healthy. Glucosamine-supported diet recommended.",
    vaccinated: true,
    spayedNeutered: true,
    meetAndGreet: "Trail walk on Mount Seymour",
    adoptionFee: 600,
    status: "available",
    lastUpdated: daysAgo(4),
    createdAt: daysAgo(60),
  },
  {
    id: "p-pumpkin",
    name: "Pumpkin",
    species: "rabbit",
    breed: "Holland Lop",
    age: "1 year",
    ageGroup: "young",
    gender: "male",
    size: "small",
    weightKg: 2,
    energyLevel: "medium",
    locationCity: "Coquitlam",
    distanceKm: 22,
    shelterId: "sh-6",
    shelterName: "Lower Mainland Rabbit Rescue",
    images: ["g1", "g2"],
    bio: "Pumpkin binkies in the morning sun and loves a quiet evening cuddle. Litter-trained and ready for x-pen apartment life.",
    idealHome: "Indoor x-pen setup, ideally bonded with a rabbit friend later.",
    personalityTags: ["Curious", "Tidy", "Binkies"],
    goodWithDogs: false,
    goodWithCats: false,
    goodWithKids: true,
    medicalNotes: "Spayed. Healthy weight.",
    vaccinated: true,
    spayedNeutered: true,
    meetAndGreet: "Foster home, Coquitlam Centre",
    adoptionFee: 95,
    status: "available",
    lastUpdated: daysAgo(3),
    createdAt: daysAgo(15),
  },
  {
    id: "p-nala",
    name: "Nala",
    species: "cat",
    breed: "Tabby",
    age: "6 months",
    ageGroup: "puppy",
    gender: "female",
    size: "small",
    weightKg: 2.5,
    energyLevel: "high",
    locationCity: "Burnaby",
    distanceKm: 11,
    shelterId: "sh-5",
    shelterName: "Burnaby Friends of Felines",
    images: ["g1", "g2", "g3"],
    bio: "Nala is a bouncy kitten who will absolutely steal your hair tie. She's playful, brave, and learning manners with her foster siblings.",
    idealHome: "Active home, ideally with another playful young cat.",
    personalityTags: ["Playful", "Brave", "Kitten-zoomies"],
    goodWithDogs: true,
    goodWithCats: true,
    goodWithKids: true,
    medicalNotes: "Spay scheduled. Two rounds of vaccines complete.",
    vaccinated: true,
    spayedNeutered: false,
    meetAndGreet: "Foster home, Brentwood",
    adoptionFee: 220,
    status: "available",
    lastUpdated: daysAgo(1),
    createdAt: daysAgo(10),
  },
  {
    id: "p-cedar",
    name: "Cedar",
    species: "dog",
    breed: "Lab x Border Collie",
    age: "5 years",
    ageGroup: "adult",
    gender: "male",
    size: "large",
    weightKg: 30,
    energyLevel: "high",
    locationCity: "Surrey",
    distanceKm: 32,
    shelterId: "sh-3",
    shelterName: "Richmond Animal Protection Society",
    images: ["g1", "g2"],
    bio: "Cedar is happiest when he has a job — fetch, agility, or a long beach run. Smart, deeply loyal, and quick to bond.",
    idealHome: "Active outdoor home with a yard, no cats.",
    personalityTags: ["Energetic", "Smart", "Loyal"],
    goodWithDogs: true,
    goodWithCats: false,
    goodWithKids: true,
    medicalNotes: "Healthy.",
    vaccinated: true,
    spayedNeutered: true,
    meetAndGreet: "Shelter walk + park session",
    adoptionFee: 500,
    status: "available",
    lastUpdated: daysAgo(6),
    createdAt: daysAgo(50),
  },
  {
    id: "p-milo",
    name: "Milo",
    species: "cat",
    breed: "Russian Blue mix",
    age: "8 years",
    ageGroup: "senior",
    gender: "male",
    size: "medium",
    weightKg: 5.5,
    energyLevel: "low",
    locationCity: "Burnaby",
    distanceKm: 13,
    shelterId: "sh-5",
    shelterName: "Burnaby Friends of Felines",
    images: ["g1", "g2"],
    bio: "Milo is a thoughtful senior gentleman who loves slow mornings and quiet podcast afternoons. A perfect work-from-home companion.",
    idealHome: "Calm only-cat home or with another mellow senior.",
    personalityTags: ["Wise", "Mellow", "Lap cat"],
    goodWithDogs: false,
    goodWithCats: true,
    goodWithKids: true,
    medicalNotes: "Early kidney support diet. Annual bloodwork advised.",
    vaccinated: true,
    spayedNeutered: true,
    meetAndGreet: "Foster home, Metrotown",
    adoptionFee: 90,
    status: "available",
    lastUpdated: daysAgo(8),
    createdAt: daysAgo(80),
  },
  {
    id: "p-ruby",
    name: "Ruby",
    species: "dog",
    breed: "Pit mix",
    age: "3 years",
    ageGroup: "young",
    gender: "female",
    size: "medium",
    weightKg: 22,
    energyLevel: "medium",
    locationCity: "Richmond",
    distanceKm: 18,
    shelterId: "sh-3",
    shelterName: "Richmond Animal Protection Society",
    images: ["g1", "g2", "g3"],
    bio: "Ruby is a wiggle-bottomed sweetheart who turns into a couch puddle after her walk. Wonderful with adults and patient kids.",
    idealHome: "Adult or teen household. No cats. Loves a fenced yard.",
    personalityTags: ["Snuggly", "Velcro", "Goofy"],
    goodWithDogs: true,
    goodWithCats: false,
    goodWithKids: true,
    medicalNotes: "Healthy. Mild leash reactivity, training plan included.",
    vaccinated: true,
    spayedNeutered: true,
    meetAndGreet: "Shelter intro + walk",
    adoptionFee: 400,
    status: "pending",
    lastUpdated: daysAgo(2),
    createdAt: daysAgo(35),
  },
  {
    id: "p-otis",
    name: "Otis",
    species: "dog",
    breed: "Dachshund",
    age: "9 years",
    ageGroup: "senior",
    gender: "male",
    size: "small",
    weightKg: 6,
    energyLevel: "low",
    locationCity: "New Westminster",
    distanceKm: 16,
    shelterId: "sh-1",
    shelterName: "Pacific Coast SPCA — Vancouver",
    images: ["g1", "g2"],
    bio: "Otis is a snoring, sun-following little gentleman. He'll trade you a small walk for a long cuddle, every time.",
    idealHome: "Apartment or condo. Quiet adult home.",
    personalityTags: ["Cuddly", "Apartment-perfect", "Gentle"],
    goodWithDogs: true,
    goodWithCats: true,
    goodWithKids: false,
    medicalNotes: "Manages mild back sensitivity. No stairs preferred.",
    vaccinated: true,
    spayedNeutered: true,
    meetAndGreet: "Shelter visit",
    adoptionFee: 250,
    status: "available",
    lastUpdated: daysAgo(5),
    createdAt: daysAgo(55),
  },
  {
    id: "p-willow",
    name: "Willow",
    species: "cat",
    breed: "Calico",
    age: "2 years",
    ageGroup: "young",
    gender: "female",
    size: "small",
    weightKg: 3.6,
    energyLevel: "medium",
    locationCity: "Vancouver",
    distanceKm: 5,
    shelterId: "sh-2",
    shelterName: "Orphan Kitten Project",
    images: ["g1", "g2"],
    bio: "Willow is a thoughtful observer who warms up beautifully once she trusts you. She'd love a patient adopter with a sunny window seat.",
    idealHome: "Quiet only-cat home. Patient adopter.",
    personalityTags: ["Shy at first", "Loyal", "Window-watcher"],
    goodWithDogs: false,
    goodWithCats: true,
    goodWithKids: false,
    medicalNotes: "Healthy.",
    vaccinated: true,
    spayedNeutered: true,
    meetAndGreet: "Foster home, Mount Pleasant",
    adoptionFee: 200,
    status: "available",
    lastUpdated: daysAgo(7),
    createdAt: daysAgo(45),
  },
  {
    id: "p-pepper",
    name: "Pepper",
    species: "small",
    breed: "Guinea pig pair",
    age: "1 year",
    ageGroup: "young",
    gender: "female",
    size: "small",
    weightKg: 1,
    energyLevel: "low",
    locationCity: "Coquitlam",
    distanceKm: 24,
    shelterId: "sh-6",
    shelterName: "Lower Mainland Rabbit Rescue",
    images: ["g1", "g2"],
    bio: "Pepper and her sister Salt are a bonded guinea pig duo who whistle for their morning veggies. Adopted as a pair.",
    idealHome: "Indoor large C&C habitat. Family-friendly.",
    personalityTags: ["Bonded pair", "Vocal", "Sweet"],
    goodWithDogs: false,
    goodWithCats: false,
    goodWithKids: true,
    medicalNotes: "Healthy. Vitamin C diet plan included.",
    vaccinated: false,
    spayedNeutered: false,
    meetAndGreet: "Foster home, Burquitlam",
    adoptionFee: 60,
    status: "available",
    lastUpdated: daysAgo(12),
    createdAt: daysAgo(28),
  },
  {
    id: "p-biscuit",
    name: "Biscuit",
    species: "dog",
    breed: "Golden Retriever",
    age: "1 year",
    ageGroup: "young",
    gender: "male",
    size: "large",
    weightKg: 28,
    energyLevel: "high",
    locationCity: "Langley",
    distanceKm: 40,
    shelterId: "sh-3",
    shelterName: "Richmond Animal Protection Society",
    images: ["g1", "g2", "g3"],
    bio: "Biscuit is exactly as joyful as his name suggests. He's still learning leash manners and would thrive with a patient, active family.",
    idealHome: "Active family home with a yard. Training time available.",
    personalityTags: ["Joyful", "Trainable", "Family-friendly"],
    goodWithDogs: true,
    goodWithCats: true,
    goodWithKids: true,
    medicalNotes: "Healthy.",
    vaccinated: true,
    spayedNeutered: false,
    meetAndGreet: "Shelter + obedience session",
    adoptionFee: 550,
    status: "available",
    lastUpdated: daysAgo(45),
    createdAt: daysAgo(90),
  },
];

export function getPet(id: string) {
  return PETS.find((p) => p.id === id);
}
export function getShelter(id: string) {
  return SHELTERS.find((s) => s.id === id);
}
export function petsByShelter(id: string) {
  return PETS.filter((p) => p.shelterId === id);
}
